image: php:8.2

stages:
  - build
  - test

job-composer:
  stage: build
  before_script:
    - echo "Running Composer Job"
  script:
    - apt-get update -yq && apt-get install -y unzip git libzip-dev
    - docker-php-ext-install zip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer config cache-files-dir $COMPOSER_CACHE_DIR
    - composer install --prefer-dist --no-progress --no-suggest
  artifacts:
    untracked: true
    paths:
      - vendor/
      - composer.lock

job-phpstan:
  stage: test
  before_script:
    - echo "Running PHPStan code analysis"
  script:
    - php ./vendor/bin/phpstan analyze -c phpstan.neon --no-progress --error-format gitlab > ./phpstan-report.json
  artifacts:
    paths:
      - ./phpstan-report.json
    expire_in: 1 hour
    when: always
    reports:
      codequality: "./phpstan-report.json"
  allow_failure: true