image: php:8.2

stages:
  - build

job-composer:
  stage: build
  before-script:
    - echo "Running Composer Job"
  script:
    - apt-get update -yq && apt-get install -y unzip git libzip-dev
    - docker-php-ext-install zip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer config cache-files-dir $COMPOSER_CACHE_DIR
    - composer install --prefer-dist --no-progress --no-suggest
  artifacts:
    untracked: true
    paths:
      - vendor/